### ISSUE TITLE
Add feature that allows a user to adjust the test list.

### ISSUE THREAD

**Issue by gudnimg** [Ingimarsson/pluto-issues#16]
Example: Here it would be handy to have the Smoke test as the first on the list. This make it seem "the logical choice" as a first test. But currently this list cannot be row adjusted.
![image](https://user-images.githubusercontent.com/8218499/75260441-85118f00-57e1-11ea-9ab7-3145cf6e9b55.png)

**Comment by Ingimarsson** [comment]
Tests are now sorted by the order property, an integer which can be adjusted for each project (see screenshot)

This can later be replaced with a drag-and-drop based solution, but that will take time to implement.

### screenshot

![image](https://user-images.githubusercontent.com/3607456/75376075-51a93000-58c7-11ea-82d5-99b4a3a52071.png)
