### ISSUE TITLE
"Group" in Event is hardcoded "Aerodynamics"

### ISSUE THREAD

**Issue by gudnimg** [Ingimarsson/pluto-issues#17]
The Group in Events page is correct:
![image](https://user-images.githubusercontent.com/8218499/75268964-1687fd80-57f0-11ea-95c5-4ada5f438d3a.png)

But the group within the Event is hardcoded "Aerodynamics"
![image](https://user-images.githubusercontent.com/8218499/75268998-269fdd00-57f0-11ea-9518-9c7be9dfabbe.png)

**Comment by Ingimarsson** [comment]
Fix has been committed.
