### ISSUE TITLE
Add color to project's test "status"

### ISSUE THREAD

**Issue by gudnimg** [Ingimarsson/pluto-issues#21]
Add color to status as can be view below: 
![image](https://user-images.githubusercontent.com/8218499/75288037-675d1d80-5813-11ea-80ee-60a2dde317ee.png)

To be consistent with the test run status:
![image](https://user-images.githubusercontent.com/8218499/75288097-8360bf00-5813-11ea-9327-a30e3e4472a0.png)

**Comment by Ingimarsson** [comment]
Fix has been committed.
