### ISSUE TITLE
Can't create task for project.

### ISSUE THREAD

**Issue by gudnimg** [Ingimarsson/pluto-issues#22]
Currently in pluto 3.1 users cannot create tasks within a project.

![image](https://user-images.githubusercontent.com/8218499/75624488-8dd0df00-5bac-11ea-9ec9-f1e1c3276da9.png)

It should look like this: 

![image](https://user-images.githubusercontent.com/8218499/75624508-b2c55200-5bac-11ea-9a9c-17f30c58a883.png)

**Comment by Ingimarsson** [comment]
Duplicate of #7
