### ISSUE TITLE
Navigating from Project tasks to Tasks on top of page results in a blank page. 

### ISSUE THREAD

**Issue by gudnimg** [Ingimarsson/pluto-issues#23]
How to reproduce:

1. Navigate to a project's task list.

![image](https://user-images.githubusercontent.com/8218499/75624530-ee601c00-5bac-11ea-8fe4-74dcd02212c7.png)

2. Click on Tasks tab on top of page.

![image](https://user-images.githubusercontent.com/8218499/75624539-0172ec00-5bad-11ea-981a-1f3cc730b51a.png)

3. You get a blank page:

![image](https://user-images.githubusercontent.com/8218499/75624542-1485bc00-5bad-11ea-8efe-71a8db7e6785.png)

**Comment by Ingimarsson** [comment]
Fix has been committed. Had to move DndProvider to top-level.
