### ISSUE TITLE
In Tasks when clicking on Project, but not clicking any new project, the project gets automatically changed.

### ISSUE THREAD

**Issue by gudnimg** [Ingimarsson/pluto-issues#27]
If a user clicks on the tab but then click anywhere else on the screen to cancel the drop down list the top most project in the list gets automatically assigned.

![image](https://user-images.githubusercontent.com/8218499/75707300-94e41400-5cb6-11ea-962d-15435b0d3deb.png)

This should not change the current project if the user does not intentionally select a new project from the drop down list.

**Comment by Ingimarsson** [comment]
This will be fixed with #25
