### ISSUE TITLE
In Tasks when changing the Project assigned, the entire list is not viewable.

### ISSUE THREAD

**Issue by gudnimg** [Ingimarsson/pluto-issues#28]
It is not possible to scroll down the "Project" list. For example in this example below I cannot find AMS.

![image](https://user-images.githubusercontent.com/8218499/75707499-e096bd80-5cb6-11ea-8c2a-ea7cb0aabe08.png)

**Comment by Ingimarsson** [comment]
This will be fixed with #25 making the dropdown scrollable
