### ISSUE TITLE
Test documentation template

### ISSUE THREAD

**Issue by KristjanOrn** [Ingimarsson/pluto-issues#35]
When creating a new test and test run a template should appear in the Markdown window.
Example Test Description template:

## Test description
_Test purpose and useful information_

## Test Procedure
1. _Step one_
2. _Step two_
3. 
4.

## Test Pass criteria
- 
-
-

## Required Deliverable's
- _Information that needs registered if applicable_

Test run template:

**Equipment Used:**
- 
- 

**Test Results**
-
-

**Test is ---**

**Comment by Ingimarsson** [comment]
Good idea, hard coded for the moment until an admin settings system has been implemented.
