### ISSUE TITLE
Test information display opens when deleting a task

### ISSUE THREAD

**Issue by KristjanOrn** [Ingimarsson/pluto-issues#8]
Task information dialog opens after deleting a task with a loading icon. The dialog can be closed with a mouse click outside the dialog.
Server gives "Resource not found" error

![image](https://user-images.githubusercontent.com/19389706/75144531-076d5680-56ef-11ea-85f7-432ad3229f7f.png)

**Comment by Ingimarsson** [comment]
Fix has been committed.
